'use client';
import { useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { PhysicsSandbox } from './PhysicsSandbox';
import { RoundSummary } from './RoundSummary';
import { ToolInventory } from './ToolInventory';
import { getGravityPuzzle } from './tasks';
import { GravityGrade, PlacedShape, ShapeType } from './types';

const GAME_KEY='gravity_workshop';
export function GravityWorkshopGame(){
const [grade,setGrade]=useState<GravityGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [puzzle,setPuzzle]=useState(()=>getGravityPuzzle('2nd')); const [available,setAvailable]=useState<ShapeType[]>([]); const [shapes,setShapes]=useState<PlacedShape[]>([]); const [attempts,setAttempts]=useState(0); const [streak,setStreak]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const completion = useMemo(()=>Math.min(100, Math.round((shapes.length/Math.max(1,puzzle.goal_conditions.minStableObjects??3))*100)),[shapes.length,puzzle.goal_conditions.minStableObjects]);
const startRound=()=>{const p=getGravityPuzzle(grade); setPuzzle(p); setAvailable([...p.available_shapes].sort(()=>Math.random()-0.5)); setShapes([]); setAttempts(0); setStreak(0); setXpEarned(0); setSyncWarning(''); setStatus('running');};
const onDrop=(shapeType:string,x:number,y:number)=>{ if(status!=='running')return; const idx=available.findIndex((s)=>s===shapeType); if(idx===-1) return; setAvailable((v)=>v.filter((_,i)=>i!==idx)); setShapes((s)=>[...s,{id:`${shapeType}-${Date.now()}`,type:shapeType as ShapeType,x,y,rotation:0,vy:0,stableTicks:0}]); playCorrectSound(soundOn);};
const simulate=()=>{ setAttempts((a)=>a+1); const stable=shapes.length>=(puzzle.goal_conditions.minStableObjects??0); const circleInTarget=!puzzle.goal_conditions.ballInTarget||shapes.some((s)=>s.type==='circle'&&s.x>270&&s.y>250); if(stable&&circleInTarget){ setStreak((s)=>s+1); setXpEarned((x)=>x+puzzle.xp_value); playCorrectSound(soundOn);} else { setStreak(0); playTryAgainSound(soundOn);} };
const endRound=async()=>{ const success=completion>=100; let roundXP=xpEarned+(success?20:0)+(attempts<=1?15:0); const creativity=shapes.filter((s)=>s.type==='triangle'||s.type==='ramp').length*2; roundXP+=creativity; const previous=await getUserGameProgress('local-user',GAME_KEY); if((success?1:0)>(previous?.best_score??0)) roundXP+=20; const updated=(previous?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{ await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(previous?.best_score??0,success?1:0),total_sessions:(previous?.total_sessions??0)+1,total_correct:(previous?.total_correct??0)+(success?1:0),total_attempts:(previous?.total_attempts??0)+attempts,accuracy:completion,current_difficulty:puzzle.difficulty,settings:{best_streak:streak,mastered_puzzle_types:[puzzle.task_type],game_specific_stats:{puzzles_completed:success?1:0,average_attempts:attempts,stability_score:completion,object_types_used:[...new Set(shapes.map((s)=>s.type))]}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
return <main className='min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-sky-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Gravity Workshop' grade={grade} xpEarned={xpEarned} accuracyLabel={`Puzzle progress: ${completion}%`} streak={streak}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as GravityGrade)}/>}<section className='rounded-2xl bg-white/95 p-4 text-slate-900'><p className='text-sm font-semibold text-indigo-700'>{puzzle.instruction}</p><p className='text-sm text-slate-700'>{attempts>0?'Try another idea! Move pieces and simulate again.':'Drag tools into the lab and press Simulate.'}</p></section><PhysicsSandbox shapes={shapes} targetGlow={completion>=100} onDrop={onDrop}/><ToolInventory shapes={available}/><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={simulate} className='min-h-11 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white'>Simulate</button><button onClick={()=>setShapes([])} className='min-h-11 rounded-xl bg-slate-700 px-4 py-2 font-semibold text-white'>Reset Puzzle</button></GameControlRow>{status==='ended'&&<RoundSummary xpEarned={xpEarned} completion={completion} creativity={shapes.length*2} efficiency={Math.max(0,100-attempts*10)} attempts={attempts} level={calculateLevelFromXP(totalXP)} onPlayAgain={()=>setStatus('ready')} syncWarning={syncWarning}/>}</div></main>
}
