'use client';
import { useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { getScenario } from './scenarios';
import { ShakerzGrade } from './types';
import { RoundSummary } from './RoundSummary';
const GAME_KEY='shakerz';
export function ShakerzGame(){const [grade,setGrade]=useState<ShakerzGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [scenario,setScenario]=useState(()=>getScenario('2nd')); const [attempts,setAttempts]=useState(0); const [correct,setCorrect]=useState(0); const [streak,setStreak]=useState(0); const [bestStreak,setBestStreak]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [reaction,setReaction]=useState('Tiny world is ready!'); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [largeTargets,setLargeTargets]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((correct/attempts)*100):0; const progress=Math.min(100,Math.round((correct/Math.max(1,scenario.clickable_targets.filter(t=>t.correct).length))*100));
const startRound=()=>{setScenario(getScenario(grade)); setAttempts(0); setCorrect(0); setStreak(0); setBestStreak(0); setXpEarned(0); setReaction('Tiny world is ready!'); setSyncWarning(''); setStatus('running');};
const clickTarget=(ok:boolean,label:string)=>{if(status!=='running')return; setAttempts(a=>a+1); if(ok){const ns=streak+1; setCorrect(c=>c+1); setStreak(ns); setBestStreak(b=>Math.max(b,ns)); setXpEarned(x=>x+5); setReaction(`${label} clicked! ${scenario.environment_reactions[Math.floor(Math.random()*scenario.environment_reactions.length)]}`); playCorrectSound(soundOn);} else {setStreak(0); setReaction('Nice try! Another target is wobbling nearby.'); playTryAgainSound(soundOn);} };
const endRound=async()=>{let roundXP=xpEarned+20; if(accuracy>80) roundXP+=15; const prev=await getUserGameProgress('local-user',GAME_KEY); if(correct>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,correct),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+correct,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:scenario.difficulty,settings:{best_streak:bestStreak,mastered_categories:[scenario.educational_category],game_specific_stats:{click_accuracy:accuracy,combo_chain_length:bestStreak,scenarios_completed:progress===100?1:0,educational_mastery:scenario.educational_category,assist_mode_used:largeTargets}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const mastery=useMemo(()=>`${scenario.educational_category} recognition`,[scenario.educational_category]);
return <main className='min-h-screen bg-gradient-to-b from-slate-900 via-emerald-900 to-sky-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Shakerz' grade={grade} xpEarned={xpEarned} accuracyLabel={`Accuracy: ${accuracy}% • Scenario: ${progress}%`} streak={streak}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as ShakerzGrade)}/>}<section className={`rounded-2xl p-4 ring-1 ring-emerald-300/30 ${reducedMotion?'bg-white/10':'bg-[linear-gradient(135deg,rgba(16,185,129,.2),rgba(59,130,246,.2))]'}`}><p className='text-sm text-emerald-100'>Scene: {scenario.scenario_type} • Objective: {scenario.objective}</p><div className='mt-3 grid gap-2 sm:grid-cols-2 md:grid-cols-3'>{scenario.clickable_targets.map((t,i)=><button key={`${t.label}-${i}`} onClick={()=>clickTarget(t.correct,t.label)} className={`${largeTargets?'min-h-20 text-lg':'min-h-14'} rounded-xl border border-emerald-200/50 bg-slate-900/60 px-3 py-2 font-semibold text-white hover:bg-slate-800`}>{t.label}</button>)}</div><p className='mt-3 text-sm text-emerald-100'>Reaction: {reaction}</p></section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={()=>setLargeTargets(v=>!v)} className='min-h-11 rounded-xl bg-slate-700 px-4 py-2 font-semibold text-white'>{largeTargets?'Normal Targets':'Larger Targets'}</button></GameControlRow>{status==='ended'&&<RoundSummary xpEarned={xpEarned} accuracy={accuracy} targetsCompleted={correct} bestStreak={bestStreak} mastery={mastery} scenarioProgress={progress} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main> }
