'use client';
import { useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { getPairs } from './pairs';
import { MatchCard, MemoryGrade } from './types';
import { RoundSummary } from './RoundSummary';
const GAME_KEY='memory_match';
export function MemoryMatchGame(){const [grade,setGrade]=useState<MemoryGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [cards,setCards]=useState<MatchCard[]>([]); const [selected,setSelected]=useState<string[]>([]); const [attempts,setAttempts]=useState(0); const [matches,setMatches]=useState(0); const [streak,setStreak]=useState(0); const [bestStreak,setBestStreak]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((matches/attempts)*100):0;
const startRound=()=>{const pairCount=grade==='Kindergarten'?2:grade==='1st'||grade==='2nd'?4:6; const pairs=getPairs(grade,pairCount); const deck=pairs.flatMap((p,i)=>[{id:`${i}-a`,pairId:`p${i}`,content:p.card_a,revealed:false,matched:false},{id:`${i}-b`,pairId:`p${i}`,content:p.card_b,revealed:false,matched:false}]).sort(()=>Math.random()-0.5); setCards(deck); setSelected([]); setAttempts(0); setMatches(0); setStreak(0); setBestStreak(0); setXpEarned(0); setSyncWarning(''); setStatus('running');};
const flip=(id:string)=>{ if(status!=='running')return; const c=cards.find(c=>c.id===id); if(!c||c.revealed||c.matched||selected.length===2) return; const next=[...selected,id]; setCards(cs=>cs.map(card=>card.id===id?{...card,revealed:true}:card)); setSelected(next); if(next.length===2){ setAttempts(a=>a+1); const [a,b]=next.map(n=>cards.find(c=>c.id===n)).filter(Boolean) as MatchCard[]; if(a&&b&&a.pairId===b.pairId){ const ns=streak+1; setStreak(ns); setBestStreak(v=>Math.max(v,ns)); setMatches(m=>m+1); setXpEarned(x=>x+8); setCards(cs=>cs.map(card=>card.id===a.id||card.id===b.id?{...card,matched:true}:card)); setSelected([]); playCorrectSound(soundOn);} else {setStreak(0); playTryAgainSound(soundOn); setTimeout(()=>{setCards(cs=>cs.map(card=>next.includes(card.id)&&!card.matched?{...card,revealed:false}:card)); setSelected([]);}, reducedMotion?150:650);} }
};
const endRound=async()=>{let roundXP=xpEarned+20; if(accuracy>80) roundXP+=15; const prev=await getUserGameProgress('local-user',GAME_KEY); if(matches>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,matches),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+matches,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:grade,settings:{best_streak:bestStreak,mastered_categories:[...new Set(cards.map(c=>c.content))],mastered_pair_types:['memory_match'],game_specific_stats:{memory_accuracy:accuracy,combo_chain_length:bestStreak,average_attempts_per_match:matches?attempts/matches:attempts}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const mastery=useMemo(()=>grade==='Kindergarten'?'Shape and letter recall':grade==='4th'||grade==='5th'?'Advanced concept matching':'Vocabulary and concept matching',[grade]);
return <main className='min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-sky-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Memory Match' grade={grade} xpEarned={xpEarned} accuracyLabel={`Matches: ${matches} • Accuracy: ${accuracy}%`} streak={streak}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as MemoryGrade)}/>}<section className='rounded-2xl bg-white/10 p-4 ring-1 ring-sky-300/20'><p className='text-sm text-sky-100'>Match the educational pairs. Build a calm recall streak.</p></section><section className={`grid gap-3 ${cards.length<=6?'grid-cols-3':'grid-cols-4 sm:grid-cols-4'}`}>{cards.map(card=><button key={card.id} onClick={()=>flip(card.id)} className={`min-h-20 rounded-xl border px-2 py-3 text-center font-semibold ${card.matched?'border-emerald-300 bg-emerald-300/30':card.revealed?'border-cyan-300 bg-cyan-300/20':'border-slate-600 bg-slate-800'} ${grade==='Kindergarten'?'text-xl':'text-sm sm:text-base'}`}>{card.revealed||card.matched?card.content:'?'}</button>)}</section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={()=>setCards(cs=>cs.map(c=>({...c,revealed:true})))} className='min-h-11 rounded-xl bg-slate-700 px-4 py-2 font-semibold text-white'>Hint Reveal</button><button onClick={startRound} className='min-h-11 rounded-xl bg-slate-700 px-4 py-2 font-semibold text-white'>Restart Board</button></GameControlRow>{status==='ended'&&<RoundSummary xpEarned={xpEarned} matchesCompleted={matches} accuracy={accuracy} memoryStreak={bestStreak} mastery={mastery} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main> }
