'use client';
import { useEffect, useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { KeyboardCoachDock } from '@/components/gaming/keyboard-coach/KeyboardCoachDock';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { FallingLetter, DropletGrade } from './types';
import { pickDropletWord } from './words';
import { RoundSummary } from './RoundSummary';
const GAME_KEY='droplets';
export function DropletsGame(){const [grade,setGrade]=useState<DropletGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [word,setWord]=useState(()=>pickDropletWord('2nd')); const [letters,setLetters]=useState<FallingLetter[]>([]); const [typedIndex,setTypedIndex]=useState(0); const [attempts,setAttempts]=useState(0); const [correct,setCorrect]=useState(0); const [streak,setStreak]=useState(0); const [bestStreak,setBestStreak]=useState(0); const [wordsDone,setWordsDone]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [timeLeft,setTimeLeft]=useState(80); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((correct/attempts)*100):0;
useEffect(()=>{if(status!=='running')return; const t=setInterval(()=>setTimeLeft(v=>Math.max(0,v-1)),1000); return ()=>clearInterval(t);},[status]);
useEffect(()=>{if(status!=='running')return; const t=setInterval(()=>setLetters(prev=>prev.map(l=>l.stabilized?l:{...l,y:l.y+word.letter_speed}).filter(l=>l.y<94)),300); return ()=>clearInterval(t);},[status,word.letter_speed]);
useEffect(()=>{if(status!=='running')return; const t=setInterval(()=>{setLetters(prev=>{if(typedIndex>=word.word.length) return prev; if(prev.some(p=>p.index===typedIndex)) return prev; const letter=word.word[typedIndex]; return [...prev,{id:`${letter}-${Date.now()}`,letter,index:typedIndex,y:8,stabilized:false}];});},word.droplet_spacing); return ()=>clearInterval(t);},[status,typedIndex,word]);
useEffect(()=>{if(timeLeft===0&&status==='running') void endRound();},[timeLeft,status]);
const startRound=()=>{const nw=pickDropletWord(grade); setWord(nw); setLetters([]); setTypedIndex(0); setAttempts(0); setCorrect(0); setStreak(0); setBestStreak(0); setWordsDone(0); setXpEarned(0); setTimeLeft(grade==='Kindergarten'||grade==='1st'?90:80); setSyncWarning(''); setStatus('running');};
const onKey=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(status!=='running')return; const key=e.key.toLowerCase(); if(key.length!==1)return; setAttempts(a=>a+1); const expected=word.word[typedIndex]?.toLowerCase(); if(key===expected){setCorrect(c=>c+1); const ns=streak+1; setStreak(ns); setBestStreak(b=>Math.max(b,ns)); setXpEarned(x=>x+word.xp_value/Math.max(1,word.word.length)); setLetters(prev=>prev.map(l=>l.index===typedIndex?{...l,stabilized:true}:l)); const next=typedIndex+1; setTypedIndex(next); playCorrectSound(soundOn); if(next>=word.word.length){ setWordsDone(w=>w+1); setTypedIndex(0); setLetters([]); setWord(pickDropletWord(grade)); /* pronunciation hook */ }} else {setStreak(0); playTryAgainSound(soundOn);} };
const endRound=async()=>{let roundXP=Math.round(xpEarned)+20; if(accuracy>85) roundXP+=15; const prev=await getUserGameProgress('local-user',GAME_KEY); if(wordsDone>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,wordsDone),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+correct,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:word.difficulty,settings:{best_streak:bestStreak,mastered_categories:[word.category],mastered_words:[word.word],game_specific_stats:{words_completed:wordsDone,typing_speed:correct,phonics_accuracy:accuracy,combo_chain_length:bestStreak,keyboard_coach_used:true,pronunciation_plays:wordsDone}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const targetLetter=word.word[typedIndex] ?? '';
return <main className='min-h-screen bg-gradient-to-b from-cyan-950 via-blue-900 to-indigo-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Droplets' grade={grade} xpEarned={Math.round(xpEarned)} accuracyLabel={`Accuracy: ${accuracy}% • Rain progress: ${Math.min(100,wordsDone*20)}%`} streak={streak} timeRemaining={timeLeft}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as DropletGrade)}/>}<section className='relative h-[360px] overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_20%_20%,rgba(56,189,248,.22),transparent_45%),#082f49] ring-1 ring-cyan-300/30'>{letters.map(l=><div key={l.id} style={{left:`${18+l.index*12}%`,top:`${l.y}%`}} className={`absolute -translate-x-1/2 rounded-full px-3 py-2 font-bold ${l.stabilized?'bg-emerald-300 text-slate-900':'bg-cyan-300 text-slate-900'}`}>{l.letter.toUpperCase()}</div>)}<div className='absolute bottom-4 left-1/2 -translate-x-1/2 rounded bg-white/90 px-4 py-2 text-slate-900'>Word build: {word.word.split('').map((c,i)=><span key={`${c}-${i}`} className={`mx-1 inline-block min-w-8 rounded px-2 py-1 ${i<typedIndex?'bg-emerald-200':'bg-slate-200'}`}>{i<typedIndex?c.toUpperCase():'_'}</span>)}</div></section><section className='rounded-2xl bg-white/10 p-4 ring-1 ring-cyan-300/20'><p className='text-sm text-cyan-100'>Target letter: <b>{targetLetter.toUpperCase() || '—'}</b></p><input onKeyDown={onKey} className='mt-2 w-full rounded-xl border-2 border-cyan-400 bg-slate-950 px-4 py-3 text-lg text-white' placeholder='Type letters as droplets fall' disabled={status!=='running'} /><p className='mt-2 text-sm text-cyan-100'>Category: {word.category} • Word length: {word.word.length}</p></section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={()=>setTimeLeft((t)=>Math.max(30,t+10))} className='min-h-11 rounded-xl bg-slate-700 px-4 py-2 font-semibold text-white'>Assist: Slow Pace</button></GameControlRow><KeyboardCoachDock targets={targetLetter?[{key:targetLetter}]:[]} paused={status==='paused'}/>{status==='ended'&&<RoundSummary xpEarned={Math.round(xpEarned)} wordsCompleted={wordsDone} accuracy={accuracy} bestStreak={bestStreak} typingFluency={correct} vocabularyMastered={wordsDone} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main> }
