'use client';
import { useEffect, useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { KeyboardCoachDock } from '@/components/gaming/keyboard-coach/KeyboardCoachDock';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { RoundSummary } from './RoundSummary';
import { ActiveStormWord, StormGrade } from './types';
import { pickWord } from './words';
const GAME_KEY='word_storm';
export function WordStormGame(){const [grade,setGrade]=useState<StormGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [activeWords,setActiveWords]=useState<ActiveStormWord[]>([]); const [input,setInput]=useState(''); const [attempts,setAttempts]=useState(0); const [correct,setCorrect]=useState(0); const [combo,setCombo]=useState(0); const [bestCombo,setBestCombo]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [timeLeft,setTimeLeft]=useState(75); const [stormMeter,setStormMeter]=useState(30); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((correct/attempts)*100):0; const target=activeWords[0];
useEffect(()=>{if(status!=='running')return; const t=setInterval(()=>setTimeLeft(v=>Math.max(0,v-1)),1000); return ()=>clearInterval(t);},[status]);
useEffect(()=>{if(status!=='running')return; const t=setInterval(()=>{setActiveWords((prev)=>{const moved=prev.map(w=>({...w,y:w.y+w.speed,x:w.movement_pattern==='diagonal_drift'?w.x+0.4:w.x})).filter(w=>w.y<90); if(moved.length<3){const nw=pickWord(grade); moved.push({...nw,id:`${nw.word}-${Date.now()}`,x:10+Math.random()*70,y:5});} return moved;});},350); return ()=>clearInterval(t);},[grade,status]);
useEffect(()=>{if(timeLeft===0&&status==='running') void endRound();},[timeLeft,status]);
const startRound=()=>{setStatus('running'); setActiveWords([]); setInput(''); setAttempts(0); setCorrect(0); setCombo(0); setBestCombo(0); setXpEarned(0); setTimeLeft(grade==='Kindergarten'||grade==='1st'?90:75); setStormMeter(30); setSyncWarning('');};
const submit=()=>{if(status!=='running'||!target)return; setAttempts(a=>a+1); if(input.trim().toLowerCase()===target.word.toLowerCase()){const next=combo+1; const comboBonus=next%5===0?10:0; setCorrect(c=>c+1); setCombo(next); setBestCombo(b=>Math.max(b,next)); setXpEarned(x=>x+target.xp_value+comboBonus); setStormMeter(m=>Math.max(0,m-6)); setActiveWords((w)=>w.filter(a=>a.id!==target.id)); setInput(''); playCorrectSound(soundOn);} else {setCombo(0); setStormMeter(m=>Math.min(100,m+5)); playTryAgainSound(soundOn);} };
const endRound=async()=>{let roundXP=xpEarned+15; if(accuracy>80) roundXP+=15; const prev=await getUserGameProgress('local-user',GAME_KEY); if(correct>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,correct),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+correct,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:grade,settings:{best_combo:bestCombo,mastered_categories:[...new Set(activeWords.map(w=>w.category))],mastered_words:activeWords.map(w=>w.word),game_specific_stats:{words_typed:correct,combo_chain_length:bestCombo,vocabulary_accuracy:accuracy,keyboard_coach_used:true}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const coachWord=useMemo(()=>target?.word ?? '',[target?.word]);
return <main className='min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-cyan-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Word Storm' grade={grade} xpEarned={xpEarned} accuracyLabel={`Accuracy: ${accuracy}% • Storm: ${stormMeter}%`} streak={combo} timeRemaining={timeLeft}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as StormGrade)}/>}<section className='relative h-[360px] overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_20%_20%,rgba(56,189,248,.22),transparent_40%),#0f172a] ring-1 ring-cyan-300/30'>{activeWords.map(w=><div key={w.id} style={{left:`${w.x}%`,top:`${w.y}%`}} className={`absolute -translate-x-1/2 rounded-xl px-3 py-2 font-semibold ${target?.id===w.id?'bg-cyan-300 text-slate-900':'bg-indigo-300/90 text-slate-900'}`}>{w.word}</div>)}<div className='absolute bottom-2 left-1/2 -translate-x-1/2 rounded bg-white/90 px-3 py-2 text-slate-900'>Type words to stabilize the storm</div></section><section className='rounded-2xl bg-white/10 p-4 ring-1 ring-sky-300/20'><input value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')submit();}} placeholder='Type visible word and press Enter' disabled={status!=='running'} className='w-full rounded-xl border-2 border-cyan-400 bg-slate-950 px-4 py-3 text-lg text-white'/><p className='mt-2 text-sm text-cyan-100'>{target?`Target preview: ${target.word}`:'Press Start to begin the storm.'}</p></section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={submit} className='min-h-11 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white'>Stabilize Word</button></GameControlRow><KeyboardCoachDock targets={coachWord.split('').map((k)=>({key:k}))} paused={status==='paused'}/>{status==='ended'&&<RoundSummary xpEarned={xpEarned} wordsCompleted={correct} accuracy={accuracy} bestCombo={bestCombo} vocabularyMastered={correct} typingSpeed={Math.max(1,Math.round((correct*60)/Math.max(1,75-timeLeft)))} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main>; }
