'use client';
import { useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { KeyboardCoachDock } from '@/components/gaming/keyboard-coach/KeyboardCoachDock';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { getTrailEvent } from './events';
import { JourneySummary } from './JourneySummary';
import { TrailGrade } from './types';
const GAME_KEY='discovery_trails';
export function DiscoveryTrailsGame(){const [grade,setGrade]=useState<TrailGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [event,setEvent]=useState(()=>getTrailEvent('2nd')); const [input,setInput]=useState(''); const [attempts,setAttempts]=useState(0); const [correct,setCorrect]=useState(0); const [streak,setStreak]=useState(0); const [bestStreak,setBestStreak]=useState(0); const [completed,setCompleted]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [hintsUsed,setHintsUsed]=useState(0); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((correct/attempts)*100):0; const progress=Math.min(100,Math.round((completed/8)*100));
const startRound=()=>{setStatus('running'); setEvent(getTrailEvent(grade)); setInput(''); setAttempts(0); setCorrect(0); setStreak(0); setBestStreak(0); setCompleted(0); setXpEarned(0); setHintsUsed(0); setSyncWarning('');};
const submit=()=>{if(status!=='running')return; setAttempts((a)=>a+1); const ans=input.trim().toUpperCase(); if(event.valid_answers.includes(ans)){const ns=streak+1; setCorrect((c)=>c+1); setStreak(ns); setBestStreak((b)=>Math.max(b,ns)); setCompleted((c)=>c+1); setXpEarned((x)=>x+event.xp_value); setEvent(getTrailEvent(grade)); setInput(''); playCorrectSound(soundOn);} else {setStreak(0); setHintsUsed((h)=>h+1); playTryAgainSound(soundOn);} };
const endRound=async()=>{let roundXP=xpEarned+25; if(accuracy>85) roundXP+=15; if(hintsUsed===0) roundXP+=10; const prev=await getUserGameProgress('local-user',GAME_KEY); if(completed>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,completed),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+correct,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:event.difficulty,settings:{best_streak:Math.max(bestStreak,Number(prev?.settings?.best_streak??0)),mastered_vocabulary:event.valid_answers,mastered_event_types:[event.event_type],game_specific_stats:{journeys_completed:progress===100?1:0,events_completed:completed,typing_accuracy:accuracy,environments_visited:[event.environment],keyboard_coach_used:true}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const coachWord = useMemo(()=> event.valid_answers[0] ?? '',[event.valid_answers]);
return <main className='min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-sky-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Discovery Trails' grade={grade} xpEarned={xpEarned} accuracyLabel={`Journey progress: ${progress}%`} streak={streak}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as TrailGrade)}/>}<section className='rounded-2xl bg-white/10 p-4 ring-1 ring-sky-300/20'><p className='text-sm font-semibold text-sky-100'>Environment: {event.environment}</p><p className='mt-2 text-xl font-bold'>{event.story_text}</p><p className='mt-2 text-sm text-sky-100'>{event.prompt}</p><input value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')submit();}} placeholder='Type your response' disabled={status!=='running'} className='mt-3 w-full rounded-xl border-2 border-cyan-400 bg-slate-950 px-4 py-3 text-lg text-white'/><p className='mt-2 text-sm text-sky-100'>{hintsUsed>0?`Hint: ${event.optional_hint ?? 'Look for clue words in the story.'}`:'Read the clue words and type carefully.'}</p></section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={submit} className='min-h-11 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white'>Submit Response</button></GameControlRow><KeyboardCoachDock targets={coachWord.split('').map((k)=>({key:k}))} paused={status==='paused'}/>{status==='ended'&&<JourneySummary xpEarned={xpEarned} journeyProgress={progress} challengesCompleted={completed} accuracy={accuracy} vocabMastered={correct} typingProgress={accuracy} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main> }
