'use client';
import { useMemo, useState } from 'react';
import { GradeSelector } from '@/components/gaming/GradeSelector';
import { GameControlRow } from '@/components/gaming/shared/GameControlRow';
import { GameTopBar } from '@/components/gaming/shared/GameTopBar';
import { KeyboardCoachDock } from '@/components/gaming/keyboard-coach/KeyboardCoachDock';
import { calculateLevelFromXP, getUserGameProgress, saveUserGameProgress } from '@/lib/gaming/progress';
import { playCompleteSound, playCorrectSound, playTryAgainSound } from '@/lib/gaming/soundEffects';
import { getCipherPuzzle } from './puzzles';
import { CipherGrade } from './types';
import { RoundSummary } from './RoundSummary';
const GAME_KEY='cipher_quest';
export function CipherQuestGame(){const [grade,setGrade]=useState<CipherGrade>('2nd'); const [status,setStatus]=useState<'ready'|'running'|'paused'|'ended'>('ready'); const [puzzle,setPuzzle]=useState(()=>getCipherPuzzle('2nd')); const [input,setInput]=useState(''); const [attempts,setAttempts]=useState(0); const [correct,setCorrect]=useState(0); const [streak,setStreak]=useState(0); const [bestStreak,setBestStreak]=useState(0); const [solved,setSolved]=useState(0); const [xpEarned,setXpEarned]=useState(0); const [hintsUsed,setHintsUsed]=useState(0); const [soundOn,setSoundOn]=useState(true); const [reducedMotion,setReducedMotion]=useState(false); const [syncWarning,setSyncWarning]=useState(''); const [totalXP,setTotalXP]=useState(0);
const accuracy=attempts?Math.round((correct/attempts)*100):0;
const startRound=()=>{setStatus('running'); setPuzzle(getCipherPuzzle(grade)); setInput(''); setAttempts(0); setCorrect(0); setStreak(0); setBestStreak(0); setSolved(0); setXpEarned(0); setHintsUsed(0); setSyncWarning('');};
const submit=()=>{if(status!=='running')return; setAttempts(a=>a+1); const ans=input.trim().toUpperCase(); if(puzzle.valid_answers.includes(ans)){const ns=streak+1; setCorrect(c=>c+1); setSolved(s=>s+1); setStreak(ns); setBestStreak(b=>Math.max(b,ns)); setXpEarned(x=>x+puzzle.xp_value); setInput(''); setPuzzle(getCipherPuzzle(grade)); playCorrectSound(soundOn);} else {setStreak(0); setHintsUsed(h=>h+1); playTryAgainSound(soundOn);} };
const endRound=async()=>{let roundXP=xpEarned+20; if(accuracy>85) roundXP+=15; if(hintsUsed===0) roundXP+=15; const prev=await getUserGameProgress('local-user',GAME_KEY); if(solved>(prev?.best_score??0)) roundXP+=20; const updated=(prev?.xp??totalXP)+roundXP; setXpEarned(roundXP); setTotalXP(updated); try{await saveUserGameProgress('local-user',GAME_KEY,{grade_level:grade.toLowerCase() as any,xp:updated,level:calculateLevelFromXP(updated),best_score:Math.max(prev?.best_score??0,solved),total_sessions:(prev?.total_sessions??0)+1,total_correct:(prev?.total_correct??0)+correct,total_attempts:(prev?.total_attempts??0)+attempts,accuracy,current_difficulty:puzzle.difficulty,settings:{best_streak:Math.max(bestStreak,Number(prev?.settings?.best_streak??0)),mastered_puzzle_types:[puzzle.puzzle_type],mastered_vocabulary:puzzle.valid_answers,game_specific_stats:{puzzles_completed:solved,average_hint_usage:hintsUsed,logic_accuracy:accuracy,environments_unlocked:[puzzle.environment],keyboard_coach_used:true}}});}catch{setSyncWarning('Progress will sync when available');}
playCompleteSound(soundOn); setStatus('ended');};
const coachWord=useMemo(()=>puzzle.valid_answers[0] ?? '',[puzzle.valid_answers]);
return <main className='min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-purple-900 px-4 py-6 text-white'><div className='mx-auto max-w-6xl space-y-4'><GameTopBar title='Cipher Quest' grade={grade} xpEarned={xpEarned} accuracyLabel={`Puzzle progress: ${Math.min(100,Math.round((solved/8)*100))}%`} streak={streak}/>{status==='ready'&&<GradeSelector selectedGrade={grade} onChange={(g)=>setGrade(g as CipherGrade)}/>}<section className='rounded-2xl bg-white/10 p-4 ring-1 ring-purple-300/30'><p className='text-sm text-purple-100'>Environment: {puzzle.environment}</p><p className='mt-2 text-lg font-semibold'>{puzzle.story_text}</p><p className='mt-2 text-2xl font-black tracking-widest'>{puzzle.encoded_text}</p><p className='mt-2 text-sm text-purple-100'>Clue: {hintsUsed>0?(puzzle.optional_hint ?? puzzle.clues[0]):puzzle.clues[0]}</p></section><section className='rounded-2xl bg-white/10 p-4 ring-1 ring-purple-300/30'><input value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')submit();}} placeholder='Type decoded message' disabled={status!=='running'} className='w-full rounded-xl border-2 border-violet-400 bg-slate-950 px-4 py-3 text-lg text-white'/><p className='mt-2 text-sm text-purple-100'>Decode carefully. Use the clue board before guessing.</p></section><GameControlRow status={status} onStart={startRound} onPause={()=>setStatus('paused')} onResume={()=>setStatus('running')} onEnd={()=>void endRound()} soundOn={soundOn} onToggleSound={()=>setSoundOn(v=>!v)} reducedMotion={reducedMotion} onToggleMotion={()=>setReducedMotion(v=>!v)}><button onClick={submit} className='min-h-11 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white'>Submit Decode</button></GameControlRow><KeyboardCoachDock targets={coachWord.split('').map((k)=>({key:k}))} paused={status==='paused'}/>{status==='ended'&&<RoundSummary xpEarned={xpEarned} puzzlesSolved={solved} logicAccuracy={accuracy} vocabularyMastery={correct} bestStreak={bestStreak} level={calculateLevelFromXP(totalXP)} syncWarning={syncWarning} onPlayAgain={()=>setStatus('ready')}/>}</div></main> }
